# Generated by Django 4.2 on 2026-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='source',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
